#!/bin/bash

#export BSPWM_SOCKET=/tmp/bspwm-socket


bspc monitor DP2 -n 0 -d 1 2 3 4 5 
bspc monitor DP-1 -n 1 -d 6 7 8 9 10 
bspc monitor eDP-1 -n 2 -d 11 12 13 14 15 
bspc config border_width        2
bspc config window_gap         2

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config bottom_padding	3

bspc config focused_border_color        "#364a3d"  #"#11809E"
bspc config focused_locked_border_color "#C7B579"

bspc config active_border_color         "#1a2b20"
bspc config active_locked_border_color  "#7E897F"

bspc config normal_border_color         "#21252d" #"#3F3E3B"
bspc config normal_locked_border_color  "#3F3E3B"

bspc config presel_border_color         "#A7BF81"
bspc config urgent_border_color         "#EF9AA2"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
